# Generated by Django 3.2.4 on 2021-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=100)),
                ('banner', models.URLField()),
                ('banner_link', models.URLField()),
            ],
        ),
    ]
