# Generated by Django 3.2.4 on 2021-06-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='banner',
            new_name='banner_image_link',
        ),
    ]
