# Generated by Django 3.2.4 on 2021-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_added_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_released_date',
            field=models.DateField(blank=True),
        ),
    ]
