# Generated by Django 3.2.4 on 2021-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210615_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
