# Generated by Django 3.2.4 on 2021-06-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_movie_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_released_date',
        ),
    ]
