# Generated by Django 3.2.4 on 2021-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
