# Generated by Django 3.2.4 on 2021-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
